### ISSUE TITLE
[BUG] disk.csi.akshci.com is creating a new .vhdx disk, pv & pvc for every cluster redeployment.

### ISSUE THREAD

**Issue by gittihub123** [Azure/aks-hci#195]
**Describe the bug**
I'm using the disk.csi.akshci.com plugin and want to use local storage for our cluster.
Everytime I'm redeploying my aks cluster I get a new .vhdx disk, pv and pvc. 
I want to be able to take down my cluster, and redeploy it and keep the same data on my pods.

**To Reproduce**

**Create a new akshcistoragecontainer.** 
New-AksHciStorageContainer -Name "master" -Path "C:\ClusterStorage\xxxxx\xxxxxx\data\master"

**Create a new storageclass (I create one for my master & cold storage also)**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-es-hot
provisioner: disk.csi.akshci.com
parameters:
  blocksize: "33554432"
  container: hot
  dynamic: "true"
  group: clustergroup
  hostname: ca-xxxxx
  logicalsectorsize: "4096"
  physicalsectorsize: "4096"
  port: "55000"
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

**Create my deployment (part of it)**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: esdev01t
spec:
  version: 8.3.0
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
    podTemplate:
      metadata:
        labels:
          node: master
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 0.5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: sc-es-master
  - name: hot
    count: 1
    config:
      node.roles: ["data_warm"]
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 0.5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: sc-es-hot
  - name: cold
    count: 1
    config:
      node.roles: ["data_cold"]
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 0.5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        storageClassName: sc-es-cold
  http:
    service:
      spec:
        type: LoadBalancer
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: esdev01t
spec:
  version: 8.3.0
  count: 1
  elasticsearchRef:
    name: esdev01t
    namespace: default
  http:
    service:
      spec:
        type: LoadBalancer

```
**Screenshot**
![image](https://user-images.githubusercontent.com/80075118/179233724-3978492f-0b05-4d44-82ae-e4aeab5fcfa7.png)

![image](https://user-images.githubusercontent.com/80075118/179233826-98cbfd6c-e178-44f2-9f17-1994757b4049.png)

![image](https://user-images.githubusercontent.com/80075118/179233887-02d3f143-6c82-4441-8f44-e993db31783d.png)

![image](https://user-images.githubusercontent.com/80075118/179234466-1bcd7296-d6fe-47db-bde0-40523947b978.png)

![image](https://user-images.githubusercontent.com/80075118/179234888-ceb7284a-6547-4d61-a613-883d6bf06c8e.png)

**Expected behavior**
I want to reuse my pv with the pods.

**Environment (please complete the following information):**
- OS: Azure Stack HCI 2009 10.0.20348.558
- Kubernetes Version 1.22.4
- 2 node failover cluster with S2D storage

Questions:
1. Is this the correct way to deploy my cluster with local storage?
2. If not, how should I implement my cluster with local storage on this setup?

Thank you.
